version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'lock_db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    expose:
      - "3306"

volumes:
  my-db: