version: "3.9"
services:
  app:
    build:
      context: .
      args:
        - JAR_FILE=/target/distributed-lock-0.0.1-SNAPSHOT.jar
    environment:
      - lock.datasource.url=jdbc:mysql://host.docker.internal:3306/lock_db
    deploy:
      replicas: 2